Default: &defaults
  database: myfirstyesod.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: myfirstyesod_test.sqlite3
  <<: *defaults

Staging:
  database: myfirstyesod_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: myfirstyesod_production.sqlite3
  poolsize: 100
  <<: *defaults
